
set(0,...
'DefaultTextFontsize',      14,             ...
'DefaultTextFontname',      'Helvetica',    ...
'DefaultTextFontWeight',    'bold',         ...
'DefaultAxesFontsize',      14,             ...
'DefaultAxesFontname',      'Helvetica',    ...
'DefaultAxesFontWeight',    'bold',         ...
'DefaultLineLineWidth',     2,              ...
'DefaultAxesLineWidth',     2,              ...
'DefaultFigureRenderer',    'painters',     ...
'DefaultFigureColormap',    hot);

dbstop if error


% parpool;
% clear ans